### ISSUE TITLE
cant invite bot; discord limit reached

### ISSUE THREAD

**Issue by nicxz** [Zsunamy/HLTVDiscordBridge#60] opened 2021-04-06 18:47 UTC
Hi, 

This bot is used on 100 servers, and I can't invite it to mine as there is a 100 server limit for unverified bots. Could you please get your bot verified so it can be used on more servers? For more info, see https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting 

Congrats on the succes, and thanks!

**Comment by Revilum** [comment] 2021-04-06 18:52
We are aware of that and have already applied for an official verification from discord. We applied for the queue as soon as we could but since then (2 weeks) we are still awaiting an response to our request. We'll inform you as soon as discord approves our bot application. If you really want to try our bot then my only recommendation is to try adding it to your server every few hours as sometimes an additional slot becomes available.
We are sorry for the inconvenience.

Duplicate of #49

**Closed by Revilum** 2021-04-06 18:52 UTC

**Comment by Revilum** [comment] 2021-04-16 16:13
bot is verified now so you should be able to add it to your server.
